<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Mac-mini-DuniceEdCast.local" failures="35" tests="65" name="Command line test" time="13.758" errors="0" timestamp="2021-12-27T16:47:06 MSK">
  <testcase classname="GetPostTest" name="@BeforeMethod createPost" time="0.003">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;io.restassured.response.Response.jsonPath()&amp;quot; because &amp;quot;this.response&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "io.restassured.response.Response.jsonPath()" because "this.response" is null
at GetPostTest.createPost(GetPostTest.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod createPost -->
  <testcase classname="GetPostTest" name="@BeforeMethod createPost" time="-1.640612813041E9">
    <skipped/>
  </testcase> <!-- @BeforeMethod createPost -->
  <testcase classname="GetPostTest" name="@BeforeMethod createPost" time="-1.640612813042E9">
    <skipped/>
  </testcase> <!-- @BeforeMethod createPost -->
  <testcase classname="GetPostTest" name="@BeforeMethod createPost" time="-1.640612813042E9">
    <skipped/>
  </testcase> <!-- @BeforeMethod createPost -->
  <testcase classname="GetPostTest" name="@BeforeMethod createPost" time="-1.640612813043E9">
    <skipped/>
  </testcase> <!-- @BeforeMethod createPost -->
  <testcase classname="GetPostTest" name="@BeforeMethod createPost" time="-1.640612813044E9">
    <skipped/>
  </testcase> <!-- @BeforeMethod createPost -->
  <testcase classname="GetPostTest" name="@BeforeMethod createPost" time="-1.640612813045E9">
    <skipped/>
  </testcase> <!-- @BeforeMethod createPost -->
  <testcase classname="GetPostTest" name="@BeforeMethod createPost" time="0.0">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;io.restassured.response.Response.jsonPath()&amp;quot; because &amp;quot;this.response&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "io.restassured.response.Response.jsonPath()" because "this.response" is null
at GetPostTest.createPost(GetPostTest.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod createPost -->
  <testcase classname="GetPostTest" name="@BeforeMethod createPost" time="-1.640612820618E9">
    <skipped/>
  </testcase> <!-- @BeforeMethod createPost -->
  <testcase classname="GetPostTest" name="@BeforeMethod createPost" time="-1.640612820618E9">
    <skipped/>
  </testcase> <!-- @BeforeMethod createPost -->
  <testcase classname="GetPostTest" name="@BeforeMethod createPost" time="-1.640612820619E9">
    <skipped/>
  </testcase> <!-- @BeforeMethod createPost -->
  <testcase classname="GetPostTest" name="@BeforeMethod createPost" time="-1.640612820619E9">
    <skipped/>
  </testcase> <!-- @BeforeMethod createPost -->
  <testcase classname="GetPostTest" name="@BeforeMethod createPost" time="-1.64061282062E9">
    <skipped/>
  </testcase> <!-- @BeforeMethod createPost -->
  <testcase classname="SuccessAuthorizationTest" name="successAuthorizationTest" time="0.004">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;io.restassured.response.Response.jsonPath()&amp;quot; because &amp;quot;this.response&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "io.restassured.response.Response.jsonPath()" because "this.response" is null
at SuccessAuthorizationTest.successAuthorizationTest(SuccessAuthorizationTest.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- successAuthorizationTest -->
  <testcase classname="GetFileTest" name="getFileTest" time="0.426"/>
  <testcase classname="CreatePostTest" name="createPostTest" time="0.234">
    <failure type="java.lang.IllegalArgumentException" message="Header value cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: Header value cannot be null
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.header(RequestSpecificationImpl.groovy:843)
at Methods.createPost(Methods.java:106)
at CreatePostTest.createPostTest(CreatePostTest.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 44 stack frames]]>
    </failure>
  </testcase> <!-- createPostTest -->
  <testcase classname="GetUserInfoTest" name="getUserInfoByIdTest" time="0.001">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;io.restassured.response.Response.jsonPath()&amp;quot; because &amp;quot;this.response&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "io.restassured.response.Response.jsonPath()" because "this.response" is null
at GetUserInfoTest.getUserInfoByIdTest(GetUserInfoTest.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- getUserInfoByIdTest -->
  <testcase classname="GetUserInfoTest" name="getUsers" time="0.0">
    <failure type="java.lang.IllegalArgumentException" message="Header value cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: Header value cannot be null
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.header(RequestSpecificationImpl.groovy:843)
at GetUserInfoTest.getUsers(GetUserInfoTest.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 44 stack frames]]>
    </failure>
  </testcase> <!-- getUsers -->
  <testcase classname="WrongLoginTest" name="WithoutEmail" time="1.977">
    <failure type="org.assertj.core.error.AssertJMultipleFailuresError" message="
Multiple Failures (1 failure)
-- failure 1 --
Expecting ArrayList:
 &amp;lt;[4]&amp;gt;
to contain:
 &amp;lt;[8]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8]&amp;gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (1 failure)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
at WrongLoginTest.WithoutEmail(WrongLoginTest.java:242)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- WithoutEmail -->
  <testcase classname="WrongLoginTest" name="correctEmailWithoutPassword" time="0.288">
    <failure type="org.assertj.core.error.AssertJMultipleFailuresError" message="
Multiple Failures (2 failures)
-- failure 1 --
Expecting ArrayList:
 &amp;lt;[4]&amp;gt;
to contain:
 &amp;lt;[8]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8]&amp;gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[26]&amp;gt;
but could not find the following element(s):
 &amp;lt;[26]&amp;gt;

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (2 failures)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 <[5]>
to contain:
 <[26]>
but could not find the following element(s):
 <[26]>

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:223)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- correctEmailWithoutPassword -->
  <testcase classname="WrongLoginTest" name="emptyEmail" time="0.228">
    <failure type="org.assertj.core.error.AssertJMultipleFailuresError" message="
Multiple Failures (3 failures)
-- failure 1 --
Expecting ArrayList:
 &amp;lt;[4]&amp;gt;
to contain:
 &amp;lt;[8]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8]&amp;gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[26]&amp;gt;
but could not find the following element(s):
 &amp;lt;[26]&amp;gt;

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 &amp;lt;[3]&amp;gt;
to contain:
 &amp;lt;[8]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8]&amp;gt;

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (3 failures)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 <[5]>
to contain:
 <[26]>
but could not find the following element(s):
 <[26]>

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
at WrongLoginTest.emptyEmail(WrongLoginTest.java:164)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- emptyEmail -->
  <testcase classname="WrongLoginTest" name="emptyEmailAndPassword" time="0.254">
    <failure type="org.assertj.core.error.AssertJMultipleFailuresError" message="
Multiple Failures (4 failures)
-- failure 1 --
Expecting ArrayList:
 &amp;lt;[4]&amp;gt;
to contain:
 &amp;lt;[8]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8]&amp;gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[26]&amp;gt;
but could not find the following element(s):
 &amp;lt;[26]&amp;gt;

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 &amp;lt;[3]&amp;gt;
to contain:
 &amp;lt;[8]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8]&amp;gt;

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 &amp;lt;[3]&amp;gt;
to contain:
 &amp;lt;[8, 9]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8, 9]&amp;gt;

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (4 failures)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 <[5]>
to contain:
 <[26]>
but could not find the following element(s):
 <[26]>

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8, 9]>
but could not find the following element(s):
 <[8, 9]>

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:204)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- emptyEmailAndPassword -->
  <testcase classname="WrongLoginTest" name="emptyPassword" time="0.215">
    <failure type="org.assertj.core.error.AssertJMultipleFailuresError" message="
Multiple Failures (5 failures)
-- failure 1 --
Expecting ArrayList:
 &amp;lt;[4]&amp;gt;
to contain:
 &amp;lt;[8]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8]&amp;gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[26]&amp;gt;
but could not find the following element(s):
 &amp;lt;[26]&amp;gt;

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 &amp;lt;[3]&amp;gt;
to contain:
 &amp;lt;[8]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8]&amp;gt;

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 &amp;lt;[3]&amp;gt;
to contain:
 &amp;lt;[8, 9]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8, 9]&amp;gt;

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[9]&amp;gt;
but could not find the following element(s):
 &amp;lt;[9]&amp;gt;

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (5 failures)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 <[5]>
to contain:
 <[26]>
but could not find the following element(s):
 <[26]>

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8, 9]>
but could not find the following element(s):
 <[8, 9]>

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 <[5]>
to contain:
 <[9]>
but could not find the following element(s):
 <[9]>

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
at WrongLoginTest.emptyPassword(WrongLoginTest.java:184)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- emptyPassword -->
  <testcase classname="WrongLoginTest" name="incorrectEmail1" time="0.214">
    <failure type="org.assertj.core.error.AssertJMultipleFailuresError" message="
Multiple Failures (6 failures)
-- failure 1 --
Expecting ArrayList:
 &amp;lt;[4]&amp;gt;
to contain:
 &amp;lt;[8]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8]&amp;gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[26]&amp;gt;
but could not find the following element(s):
 &amp;lt;[26]&amp;gt;

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 &amp;lt;[3]&amp;gt;
to contain:
 &amp;lt;[8]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8]&amp;gt;

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 &amp;lt;[3]&amp;gt;
to contain:
 &amp;lt;[8, 9]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8, 9]&amp;gt;

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[9]&amp;gt;
but could not find the following element(s):
 &amp;lt;[9]&amp;gt;

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 &amp;lt;[0]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (6 failures)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 <[5]>
to contain:
 <[26]>
but could not find the following element(s):
 <[26]>

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8, 9]>
but could not find the following element(s):
 <[8, 9]>

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 <[5]>
to contain:
 <[9]>
but could not find the following element(s):
 <[9]>

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- incorrectEmail1 -->
  <testcase classname="WrongLoginTest" name="incorrectEmail2" time="0.251">
    <failure type="org.assertj.core.error.AssertJMultipleFailuresError" message="
Multiple Failures (7 failures)
-- failure 1 --
Expecting ArrayList:
 &amp;lt;[4]&amp;gt;
to contain:
 &amp;lt;[8]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8]&amp;gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[26]&amp;gt;
but could not find the following element(s):
 &amp;lt;[26]&amp;gt;

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 &amp;lt;[3]&amp;gt;
to contain:
 &amp;lt;[8]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8]&amp;gt;

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 &amp;lt;[3]&amp;gt;
to contain:
 &amp;lt;[8, 9]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8, 9]&amp;gt;

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[9]&amp;gt;
but could not find the following element(s):
 &amp;lt;[9]&amp;gt;

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 &amp;lt;[0]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 &amp;lt;[0]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (7 failures)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 <[5]>
to contain:
 <[26]>
but could not find the following element(s):
 <[26]>

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8, 9]>
but could not find the following element(s):
 <[8, 9]>

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 <[5]>
to contain:
 <[9]>
but could not find the following element(s):
 <[9]>

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)
at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- incorrectEmail2 -->
  <testcase classname="WrongLoginTest" name="incorrectEmail3" time="0.294">
    <failure type="org.assertj.core.error.AssertJMultipleFailuresError" message="
Multiple Failures (8 failures)
-- failure 1 --
Expecting ArrayList:
 &amp;lt;[4]&amp;gt;
to contain:
 &amp;lt;[8]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8]&amp;gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[26]&amp;gt;
but could not find the following element(s):
 &amp;lt;[26]&amp;gt;

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 &amp;lt;[3]&amp;gt;
to contain:
 &amp;lt;[8]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8]&amp;gt;

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 &amp;lt;[3]&amp;gt;
to contain:
 &amp;lt;[8, 9]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8, 9]&amp;gt;

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[9]&amp;gt;
but could not find the following element(s):
 &amp;lt;[9]&amp;gt;

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 &amp;lt;[0]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 &amp;lt;[0]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)
-- failure 8 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:80)">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (8 failures)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 <[5]>
to contain:
 <[26]>
but could not find the following element(s):
 <[26]>

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8, 9]>
but could not find the following element(s):
 <[8, 9]>

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 <[5]>
to contain:
 <[9]>
but could not find the following element(s):
 <[9]>

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)
-- failure 8 --
Expecting ArrayList:
 <[5]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:80)
at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:81)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- incorrectEmail3 -->
  <testcase classname="WrongLoginTest" name="incorrectEmail4" time="0.225">
    <failure type="org.assertj.core.error.AssertJMultipleFailuresError" message="
Multiple Failures (9 failures)
-- failure 1 --
Expecting ArrayList:
 &amp;lt;[4]&amp;gt;
to contain:
 &amp;lt;[8]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8]&amp;gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[26]&amp;gt;
but could not find the following element(s):
 &amp;lt;[26]&amp;gt;

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 &amp;lt;[3]&amp;gt;
to contain:
 &amp;lt;[8]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8]&amp;gt;

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 &amp;lt;[3]&amp;gt;
to contain:
 &amp;lt;[8, 9]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8, 9]&amp;gt;

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[9]&amp;gt;
but could not find the following element(s):
 &amp;lt;[9]&amp;gt;

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 &amp;lt;[0]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 &amp;lt;[0]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)
-- failure 8 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:80)
-- failure 9 --
Expecting ArrayList:
 &amp;lt;[0]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail4(WrongLoginTest.java:102)">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (9 failures)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 <[5]>
to contain:
 <[26]>
but could not find the following element(s):
 <[26]>

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8, 9]>
but could not find the following element(s):
 <[8, 9]>

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 <[5]>
to contain:
 <[9]>
but could not find the following element(s):
 <[9]>

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)
-- failure 8 --
Expecting ArrayList:
 <[5]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:80)
-- failure 9 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail4(WrongLoginTest.java:102)
at WrongLoginTest.incorrectEmail4(WrongLoginTest.java:104)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- incorrectEmail4 -->
  <testcase classname="WrongLoginTest" name="incorrectEmail5" time="0.2">
    <failure type="org.assertj.core.error.AssertJMultipleFailuresError" message="
Multiple Failures (10 failures)
-- failure 1 --
Expecting ArrayList:
 &amp;lt;[4]&amp;gt;
to contain:
 &amp;lt;[8]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8]&amp;gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[26]&amp;gt;
but could not find the following element(s):
 &amp;lt;[26]&amp;gt;

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 &amp;lt;[3]&amp;gt;
to contain:
 &amp;lt;[8]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8]&amp;gt;

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 &amp;lt;[3]&amp;gt;
to contain:
 &amp;lt;[8, 9]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8, 9]&amp;gt;

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[9]&amp;gt;
but could not find the following element(s):
 &amp;lt;[9]&amp;gt;

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 &amp;lt;[0]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 &amp;lt;[0]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)
-- failure 8 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:80)
-- failure 9 --
Expecting ArrayList:
 &amp;lt;[0]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail4(WrongLoginTest.java:102)
-- failure 10 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail5(WrongLoginTest.java:123)">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (10 failures)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 <[5]>
to contain:
 <[26]>
but could not find the following element(s):
 <[26]>

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8, 9]>
but could not find the following element(s):
 <[8, 9]>

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 <[5]>
to contain:
 <[9]>
but could not find the following element(s):
 <[9]>

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)
-- failure 8 --
Expecting ArrayList:
 <[5]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:80)
-- failure 9 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail4(WrongLoginTest.java:102)
-- failure 10 --
Expecting ArrayList:
 <[5]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail5(WrongLoginTest.java:123)
at WrongLoginTest.incorrectEmail5(WrongLoginTest.java:124)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- incorrectEmail5 -->
  <testcase classname="WrongLoginTest" name="userDoesNotExist" time="0.219">
    <failure type="org.assertj.core.error.AssertJMultipleFailuresError" message="
Multiple Failures (10 failures)
-- failure 1 --
Expecting ArrayList:
 &amp;lt;[4]&amp;gt;
to contain:
 &amp;lt;[8]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8]&amp;gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[26]&amp;gt;
but could not find the following element(s):
 &amp;lt;[26]&amp;gt;

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 &amp;lt;[3]&amp;gt;
to contain:
 &amp;lt;[8]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8]&amp;gt;

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 &amp;lt;[3]&amp;gt;
to contain:
 &amp;lt;[8, 9]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8, 9]&amp;gt;

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[9]&amp;gt;
but could not find the following element(s):
 &amp;lt;[9]&amp;gt;

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 &amp;lt;[0]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 &amp;lt;[0]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)
-- failure 8 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:80)
-- failure 9 --
Expecting ArrayList:
 &amp;lt;[0]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail4(WrongLoginTest.java:102)
-- failure 10 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail5(WrongLoginTest.java:123)">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (10 failures)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 <[5]>
to contain:
 <[26]>
but could not find the following element(s):
 <[26]>

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8, 9]>
but could not find the following element(s):
 <[8, 9]>

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 <[5]>
to contain:
 <[9]>
but could not find the following element(s):
 <[9]>

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)
-- failure 8 --
Expecting ArrayList:
 <[5]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:80)
-- failure 9 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail4(WrongLoginTest.java:102)
-- failure 10 --
Expecting ArrayList:
 <[5]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail5(WrongLoginTest.java:123)
at WrongLoginTest.userDoesNotExist(WrongLoginTest.java:144)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- userDoesNotExist -->
  <testcase classname="WrongLoginTest" name="withoutEmailAndPassword" time="0.211">
    <failure type="org.assertj.core.error.AssertJMultipleFailuresError" message="
Multiple Failures (11 failures)
-- failure 1 --
Expecting ArrayList:
 &amp;lt;[4]&amp;gt;
to contain:
 &amp;lt;[8]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8]&amp;gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[26]&amp;gt;
but could not find the following element(s):
 &amp;lt;[26]&amp;gt;

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 &amp;lt;[3]&amp;gt;
to contain:
 &amp;lt;[8]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8]&amp;gt;

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 &amp;lt;[3]&amp;gt;
to contain:
 &amp;lt;[8, 9]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8, 9]&amp;gt;

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[9]&amp;gt;
but could not find the following element(s):
 &amp;lt;[9]&amp;gt;

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 &amp;lt;[0]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 &amp;lt;[0]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)
-- failure 8 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:80)
-- failure 9 --
Expecting ArrayList:
 &amp;lt;[0]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail4(WrongLoginTest.java:102)
-- failure 10 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[17]&amp;gt;
but could not find the following element(s):
 &amp;lt;[17]&amp;gt;

at WrongLoginTest.incorrectEmail5(WrongLoginTest.java:123)
-- failure 11 --
Expecting ArrayList:
 &amp;lt;[5]&amp;gt;
to contain:
 &amp;lt;[8, 26]&amp;gt;
but could not find the following element(s):
 &amp;lt;[8, 26]&amp;gt;

at WrongLoginTest.withoutEmailAndPassword(WrongLoginTest.java:259)">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (11 failures)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 <[5]>
to contain:
 <[26]>
but could not find the following element(s):
 <[26]>

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8, 9]>
but could not find the following element(s):
 <[8, 9]>

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 <[5]>
to contain:
 <[9]>
but could not find the following element(s):
 <[9]>

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)
-- failure 8 --
Expecting ArrayList:
 <[5]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:80)
-- failure 9 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail4(WrongLoginTest.java:102)
-- failure 10 --
Expecting ArrayList:
 <[5]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail5(WrongLoginTest.java:123)
-- failure 11 --
Expecting ArrayList:
 <[5]>
to contain:
 <[8, 26]>
but could not find the following element(s):
 <[8, 26]>

at WrongLoginTest.withoutEmailAndPassword(WrongLoginTest.java:259)
at WrongLoginTest.withoutEmailAndPassword(WrongLoginTest.java:261)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- withoutEmailAndPassword -->
  <testcase classname="AllNewsPageGetTest" name="allNewsPageGetTest" time="0.387"/>
  <testcase classname="DeletePostTest" name="deletePostTest" time="0.001">
    <failure type="java.lang.IllegalArgumentException" message="Header value cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: Header value cannot be null
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.header(RequestSpecificationImpl.groovy:843)
at Methods.createPost(Methods.java:106)
at DeletePostTest.deletePostTest(DeletePostTest.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 44 stack frames]]>
    </failure>
  </testcase> <!-- deletePostTest -->
  <testcase classname="GetPostTest" name="getPostTest" time="0.0">
    <skipped/>
  </testcase> <!-- getPostTest -->
  <testcase classname="GetPostTest" name="getUserPostTest" time="0.0">
    <skipped/>
  </testcase> <!-- getUserPostTest -->
  <testcase classname="WrongGetUserPostTest" name="getUserPostWithPageEqual0" time="0.0">
    <skipped/>
  </testcase> <!-- getUserPostWithPageEqual0 -->
  <testcase classname="WrongGetUserPostTest" name="getUserPostWithPerPageEqual0" time="0.0">
    <skipped/>
  </testcase> <!-- getUserPostWithPerPageEqual0 -->
  <testcase classname="WrongGetUserPostTest" name="getUserPostWithoutPage" time="0.0">
    <skipped/>
  </testcase> <!-- getUserPostWithoutPage -->
  <testcase classname="WrongGetUserPostTest" name="getUserPostWithoutPerPage" time="0.0">
    <skipped/>
  </testcase> <!-- getUserPostWithoutPerPage -->
  <testcase classname="WrongGetUserPostTest" name="getUserPostWithoutToken" time="0.0">
    <skipped/>
  </testcase> <!-- getUserPostWithoutToken -->
  <testcase classname="WrongGetFileTest" name="getFileWithoutFileNameTest" time="0.468"/>
  <testcase classname="WrongDeletePostTest" name="deletePostTestWithWrongId" time="0.0">
    <failure type="java.lang.IllegalArgumentException" message="Header value cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: Header value cannot be null
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.header(RequestSpecificationImpl.groovy:843)
at Methods.createPost(Methods.java:106)
at WrongDeletePostTest.deletePostTestWithWrongId(WrongDeletePostTest.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 44 stack frames]]>
    </failure>
  </testcase> <!-- deletePostTestWithWrongId -->
  <testcase classname="WrongDeletePostTest" name="deletePostTestWithoutToken" time="0.0">
    <failure type="java.lang.IllegalArgumentException" message="Header value cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: Header value cannot be null
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.header(RequestSpecificationImpl.groovy:843)
at Methods.createPost(Methods.java:106)
at WrongDeletePostTest.deletePostTestWithoutToken(WrongDeletePostTest.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 44 stack frames]]>
    </failure>
  </testcase> <!-- deletePostTestWithoutToken -->
  <testcase classname="WrongGetPostTest" name="getPostWithPageEqual0" time="0.207">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;java.util.List.get(int)&amp;quot; because &amp;quot;codes&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.util.List.get(int)" because "codes" is null
at WrongGetPostTest.getPostWithPageEqual0(WrongGetPostTest.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- getPostWithPageEqual0 -->
  <testcase classname="WrongGetPostTest" name="getPostWithPerPageEqual0" time="0.208">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;java.util.List.get(int)&amp;quot; because &amp;quot;codes&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.util.List.get(int)" because "codes" is null
at WrongGetPostTest.getPostWithPerPageEqual0(WrongGetPostTest.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- getPostWithPerPageEqual0 -->
  <testcase classname="WrongGetPostTest" name="getPostWithoutPage" time="0.196">
    <failure type="org.assertj.core.error.AssertJMultipleFailuresError" message="
Multiple Failures (5 failures)
-- failure 1 --
Expecting:
 &amp;lt;&amp;quot;false&amp;quot;&amp;gt;
to be equal to:
 &amp;lt;&amp;quot;true&amp;quot;&amp;gt;
but was not.
at WrongGetPostTest.getPostWithPageEqual0(WrongGetPostTest.java:62)
-- failure 2 --
Expecting actual not to be null
at WrongGetPostTest.getPostWithPageEqual0(WrongGetPostTest.java:63)
-- failure 3 --
Expecting:
 &amp;lt;&amp;quot;false&amp;quot;&amp;gt;
to be equal to:
 &amp;lt;&amp;quot;true&amp;quot;&amp;gt;
but was not.
at WrongGetPostTest.getPostWithPerPageEqual0(WrongGetPostTest.java:80)
-- failure 4 --
Expecting actual not to be null
at WrongGetPostTest.getPostWithPerPageEqual0(WrongGetPostTest.java:81)
-- failure 5 --
Expecting ArrayList:
 &amp;lt;[0]&amp;gt;
to contain:
 &amp;lt;[40]&amp;gt;
but could not find the following element(s):
 &amp;lt;[40]&amp;gt;

at WrongGetPostTest.getPostWithoutPage(WrongGetPostTest.java:28)">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (5 failures)
-- failure 1 --
Expecting:
 <"false">
to be equal to:
 <"true">
but was not.
at WrongGetPostTest.getPostWithPageEqual0(WrongGetPostTest.java:62)
-- failure 2 --
Expecting actual not to be null
at WrongGetPostTest.getPostWithPageEqual0(WrongGetPostTest.java:63)
-- failure 3 --
Expecting:
 <"false">
to be equal to:
 <"true">
but was not.
at WrongGetPostTest.getPostWithPerPageEqual0(WrongGetPostTest.java:80)
-- failure 4 --
Expecting actual not to be null
at WrongGetPostTest.getPostWithPerPageEqual0(WrongGetPostTest.java:81)
-- failure 5 --
Expecting ArrayList:
 <[0]>
to contain:
 <[40]>
but could not find the following element(s):
 <[40]>

at WrongGetPostTest.getPostWithoutPage(WrongGetPostTest.java:28)
at WrongGetPostTest.getPostWithoutPage(WrongGetPostTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- getPostWithoutPage -->
  <testcase classname="WrongGetPostTest" name="getPostWithoutPerPage" time="0.212">
    <failure type="org.assertj.core.error.AssertJMultipleFailuresError" message="
Multiple Failures (6 failures)
-- failure 1 --
Expecting:
 &amp;lt;&amp;quot;false&amp;quot;&amp;gt;
to be equal to:
 &amp;lt;&amp;quot;true&amp;quot;&amp;gt;
but was not.
at WrongGetPostTest.getPostWithPageEqual0(WrongGetPostTest.java:62)
-- failure 2 --
Expecting actual not to be null
at WrongGetPostTest.getPostWithPageEqual0(WrongGetPostTest.java:63)
-- failure 3 --
Expecting:
 &amp;lt;&amp;quot;false&amp;quot;&amp;gt;
to be equal to:
 &amp;lt;&amp;quot;true&amp;quot;&amp;gt;
but was not.
at WrongGetPostTest.getPostWithPerPageEqual0(WrongGetPostTest.java:80)
-- failure 4 --
Expecting actual not to be null
at WrongGetPostTest.getPostWithPerPageEqual0(WrongGetPostTest.java:81)
-- failure 5 --
Expecting ArrayList:
 &amp;lt;[0]&amp;gt;
to contain:
 &amp;lt;[40]&amp;gt;
but could not find the following element(s):
 &amp;lt;[40]&amp;gt;

at WrongGetPostTest.getPostWithoutPage(WrongGetPostTest.java:28)
-- failure 6 --
Expecting ArrayList:
 &amp;lt;[0]&amp;gt;
to contain:
 &amp;lt;[41]&amp;gt;
but could not find the following element(s):
 &amp;lt;[41]&amp;gt;

at WrongGetPostTest.getPostWithoutPerPage(WrongGetPostTest.java:45)">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (6 failures)
-- failure 1 --
Expecting:
 <"false">
to be equal to:
 <"true">
but was not.
at WrongGetPostTest.getPostWithPageEqual0(WrongGetPostTest.java:62)
-- failure 2 --
Expecting actual not to be null
at WrongGetPostTest.getPostWithPageEqual0(WrongGetPostTest.java:63)
-- failure 3 --
Expecting:
 <"false">
to be equal to:
 <"true">
but was not.
at WrongGetPostTest.getPostWithPerPageEqual0(WrongGetPostTest.java:80)
-- failure 4 --
Expecting actual not to be null
at WrongGetPostTest.getPostWithPerPageEqual0(WrongGetPostTest.java:81)
-- failure 5 --
Expecting ArrayList:
 <[0]>
to contain:
 <[40]>
but could not find the following element(s):
 <[40]>

at WrongGetPostTest.getPostWithoutPage(WrongGetPostTest.java:28)
-- failure 6 --
Expecting ArrayList:
 <[0]>
to contain:
 <[41]>
but could not find the following element(s):
 <[41]>

at WrongGetPostTest.getPostWithoutPerPage(WrongGetPostTest.java:45)
at WrongGetPostTest.getPostWithoutPerPage(WrongGetPostTest.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- getPostWithoutPerPage -->
  <testcase classname="WrongRegistrationTest" name="regWithEmptyAllFields" time="0.509"/>
  <testcase classname="WrongRegistrationTest" name="regWithExistingEmail" time="0.513"/>
  <testcase classname="WrongRegistrationTest" name="regWithNullAllFields" time="0.206"/>
  <testcase classname="WrongRegistrationTest" name="regWithWrongName" time="0.204"/>
  <testcase classname="WrongRegistrationTest" name="regWithWrongRole" time="0.203"/>
  <testcase classname="WrongRegistrationTest" name="regWithoutEmail" time="0.198"/>
  <testcase classname="WrongRegistrationTest" name="regWithoutName" time="0.199"/>
  <testcase classname="WrongRegistrationTest" name="regWithoutPassword" time="0.2">
    <failure type="org.assertj.core.error.AssertJMultipleFailuresError" message="
Multiple Failures (1 failure)
-- failure 1 --
Expecting ArrayList:
 &amp;lt;[30]&amp;gt;
to contain:
 &amp;lt;[25]&amp;gt;
but could not find the following element(s):
 &amp;lt;[25]&amp;gt;

at WrongRegistrationTest.regWithoutPassword(WrongRegistrationTest.java:84)">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (1 failure)
-- failure 1 --
Expecting ArrayList:
 <[30]>
to contain:
 <[25]>
but could not find the following element(s):
 <[25]>

at WrongRegistrationTest.regWithoutPassword(WrongRegistrationTest.java:84)
at WrongRegistrationTest.regWithoutPassword(WrongRegistrationTest.java:86)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- regWithoutPassword -->
  <testcase classname="WrongRegistrationTest" name="regWithoutRole" time="0.557">
    <failure type="org.assertj.core.error.AssertJMultipleFailuresError" message="
Multiple Failures (1 failure)
-- failure 1 --
Expecting ArrayList:
 &amp;lt;[30]&amp;gt;
to contain:
 &amp;lt;[25]&amp;gt;
but could not find the following element(s):
 &amp;lt;[25]&amp;gt;

at WrongRegistrationTest.regWithoutPassword(WrongRegistrationTest.java:84)">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (1 failure)
-- failure 1 --
Expecting ArrayList:
 <[30]>
to contain:
 <[25]>
but could not find the following element(s):
 <[25]>

at WrongRegistrationTest.regWithoutPassword(WrongRegistrationTest.java:84)
at WrongRegistrationTest.regWithoutRole(WrongRegistrationTest.java:99)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- regWithoutRole -->
  <testcase classname="WrongUploadFileTest" name="uploadFileWithNonFormDataTest" time="1.21"/>
  <testcase classname="UploadFileTest" name="uploadFileTest" time="0.223"/>
  <testcase classname="DeleteUserTest" name="deleteUser" time="0.515"/>
  <testcase classname="DeleteUserTest" name="deleteWithEmptyToken" time="0.677"/>
  <testcase classname="DeleteUserTest" name="deleteWithoutToken" time="0.645"/>
  <testcase classname="WrongGetUserInfoTest" name="withWrongUserId" time="0.202"/>
  <testcase classname="ChangePostTest" name="changePostTest" time="0.001">
    <failure type="java.lang.IllegalArgumentException" message="Header value cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: Header value cannot be null
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.header(RequestSpecificationImpl.groovy:843)
at Methods.createPost(Methods.java:106)
at ChangePostTest.changePostTest(ChangePostTest.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 44 stack frames]]>
    </failure>
  </testcase> <!-- changePostTest -->
  <testcase classname="GetPostTest" name="getPostTest" time="0.0">
    <skipped/>
  </testcase> <!-- getPostTest -->
  <testcase classname="GetPostTest" name="getUserPostTest" time="0.0">
    <skipped/>
  </testcase> <!-- getUserPostTest -->
  <testcase classname="WrongGetSpecificPostTest" name="getPostWithoutPageTest" time="0.0">
    <skipped/>
  </testcase> <!-- getPostWithoutPageTest -->
  <testcase classname="WrongGetSpecificPostTest" name="getPostWithoutPerPageTest" time="0.0">
    <skipped/>
  </testcase> <!-- getPostWithoutPerPageTest -->
  <testcase classname="GetPostTest" name="getPostTest" time="0.0">
    <skipped/>
  </testcase> <!-- getPostTest -->
  <testcase classname="GetPostTest" name="getUserPostTest" time="0.0">
    <skipped/>
  </testcase> <!-- getUserPostTest -->
  <testcase classname="SuccessRegistrationTest" name="registrationTest" time="0.399"/>
  <testcase classname="ChangeUserInfoTest" name="changeUserInfoSuccess" time="0.001">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;io.restassured.response.Response.jsonPath()&amp;quot; because &amp;quot;this.response&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "io.restassured.response.Response.jsonPath()" because "this.response" is null
at ChangeUserInfoTest.changeUserInfoSuccess(ChangeUserInfoTest.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- changeUserInfoSuccess -->
  <testcase classname="WrongChangePostTest" name="wrongChangePostTestWithEmptyDescription" time="0.0">
    <failure type="java.lang.IllegalArgumentException" message="Header value cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: Header value cannot be null
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.header(RequestSpecificationImpl.groovy:843)
at Methods.createPost(Methods.java:106)
at WrongChangePostTest.wrongChangePostTestWithEmptyDescription(WrongChangePostTest.java:130)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 44 stack frames]]>
    </failure>
  </testcase> <!-- wrongChangePostTestWithEmptyDescription -->
  <testcase classname="WrongChangePostTest" name="wrongChangePostTestWithEmptyTags" time="0.003">
    <failure type="java.lang.IllegalArgumentException" message="Header value cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: Header value cannot be null
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.header(RequestSpecificationImpl.groovy:843)
at Methods.createPost(Methods.java:106)
at WrongChangePostTest.wrongChangePostTestWithEmptyTags(WrongChangePostTest.java:170)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 44 stack frames]]>
    </failure>
  </testcase> <!-- wrongChangePostTestWithEmptyTags -->
  <testcase classname="WrongChangePostTest" name="wrongChangePostTestWithEmptyTitle" time="0.0">
    <failure type="java.lang.IllegalArgumentException" message="Header value cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: Header value cannot be null
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.header(RequestSpecificationImpl.groovy:843)
at Methods.createPost(Methods.java:106)
at WrongChangePostTest.wrongChangePostTestWithEmptyTitle(WrongChangePostTest.java:150)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 44 stack frames]]>
    </failure>
  </testcase> <!-- wrongChangePostTestWithEmptyTitle -->
  <testcase classname="WrongChangePostTest" name="wrongChangePostTestWithWrongId" time="0.001">
    <failure type="java.lang.IllegalArgumentException" message="Header value cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: Header value cannot be null
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.header(RequestSpecificationImpl.groovy:843)
at Methods.createPost(Methods.java:106)
at WrongChangePostTest.wrongChangePostTestWithWrongId(WrongChangePostTest.java:113)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 44 stack frames]]>
    </failure>
  </testcase> <!-- wrongChangePostTestWithWrongId -->
  <testcase classname="WrongChangePostTest" name="wrongChangePostTestWithoutDescription" time="0.001">
    <failure type="java.lang.IllegalArgumentException" message="Header value cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: Header value cannot be null
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.header(RequestSpecificationImpl.groovy:843)
at Methods.createPost(Methods.java:106)
at WrongChangePostTest.wrongChangePostTestWithoutDescription(WrongChangePostTest.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 44 stack frames]]>
    </failure>
  </testcase> <!-- wrongChangePostTestWithoutDescription -->
  <testcase classname="WrongChangePostTest" name="wrongChangePostTestWithoutImage" time="0.001">
    <failure type="java.lang.IllegalArgumentException" message="Header value cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: Header value cannot be null
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.header(RequestSpecificationImpl.groovy:843)
at Methods.createPost(Methods.java:106)
at WrongChangePostTest.wrongChangePostTestWithoutImage(WrongChangePostTest.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 44 stack frames]]>
    </failure>
  </testcase> <!-- wrongChangePostTestWithoutImage -->
  <testcase classname="WrongChangePostTest" name="wrongChangePostTestWithoutTitle" time="0.0">
    <failure type="java.lang.IllegalArgumentException" message="Header value cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: Header value cannot be null
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.header(RequestSpecificationImpl.groovy:843)
at Methods.createPost(Methods.java:106)
at WrongChangePostTest.wrongChangePostTestWithoutTitle(WrongChangePostTest.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 44 stack frames]]>
    </failure>
  </testcase> <!-- wrongChangePostTestWithoutTitle -->
  <testcase classname="WrongChangePostTest" name="wrongChangePostTestWithoutToken" time="0.0">
    <failure type="java.lang.IllegalArgumentException" message="Header value cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: Header value cannot be null
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.header(RequestSpecificationImpl.groovy:843)
at Methods.createPost(Methods.java:106)
at WrongChangePostTest.wrongChangePostTestWithoutToken(WrongChangePostTest.java:88)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 44 stack frames]]>
    </failure>
  </testcase> <!-- wrongChangePostTestWithoutToken -->
</testsuite> <!-- Command line test -->
