<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="82" passed="51" failed="31" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-12-29T18:11:03 MSK" name="Command line suite" finished-at="2021-12-29T18:12:54 MSK" duration-ms="110975">
    <groups>
    </groups>
    <test started-at="2021-12-29T18:11:03 MSK" name="Command line test" finished-at="2021-12-29T18:12:54 MSK" duration-ms="110975">
      <class name="WrongGetPostTest">
        <test-method signature="getPostWithPageEqual0()[pri:0, instance:WrongGetPostTest@65c17e38]" started-at="2021-12-29T18:12:13 MSK" name="getPostWithPageEqual0" finished-at="2021-12-29T18:12:13 MSK" duration-ms="189" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "java.util.List.contains(Object)" because "codes" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "java.util.List.contains(Object)" because "codes" is null
at WrongGetPostTest.getPostWithPageEqual0(WrongGetPostTest.java:77)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPostWithPageEqual0 -->
        <test-method signature="getPostWithPerPageEqual0()[pri:0, instance:WrongGetPostTest@65c17e38]" started-at="2021-12-29T18:12:13 MSK" name="getPostWithPerPageEqual0" finished-at="2021-12-29T18:12:13 MSK" duration-ms="187" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "java.util.List.contains(Object)" because "codes" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "java.util.List.contains(Object)" because "codes" is null
at WrongGetPostTest.getPostWithPerPageEqual0(WrongGetPostTest.java:99)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPostWithPerPageEqual0 -->
        <test-method signature="getPostWithoutPage()[pri:0, instance:WrongGetPostTest@65c17e38]" started-at="2021-12-29T18:12:13 MSK" name="getPostWithoutPage" finished-at="2021-12-29T18:12:13 MSK" duration-ms="185" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Wrong "success" expected [true] but found [false],
Wrong "success" expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Wrong "success" expected [true] but found [false],
Wrong "success" expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongGetPostTest.getPostWithoutPage(WrongGetPostTest.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPostWithoutPage -->
        <test-method signature="getPostWithoutPerPage()[pri:0, instance:WrongGetPostTest@65c17e38]" started-at="2021-12-29T18:12:13 MSK" name="getPostWithoutPerPage" finished-at="2021-12-29T18:12:13 MSK" duration-ms="179" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Wrong "success" expected [true] but found [false],
Wrong "success" expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Wrong "success" expected [true] but found [false],
Wrong "success" expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongGetPostTest.getPostWithoutPerPage(WrongGetPostTest.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPostWithoutPerPage -->
      </class> <!-- WrongGetPostTest -->
      <class name="WrongUploadFileTest">
        <test-method signature="uploadFileWithNonFormDataTest()[pri:0, instance:WrongUploadFileTest@6b63abdc]" started-at="2021-12-29T18:12:15 MSK" name="uploadFileWithNonFormDataTest" finished-at="2021-12-29T18:12:16 MSK" duration-ms="198" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- uploadFileWithNonFormDataTest -->
      </class> <!-- WrongUploadFileTest -->
      <class name="ChangePostTest">
        <test-method is-config="true" signature="reg()[pri:0, instance:ChangePostTest@551be9f6]" started-at="2021-12-29T18:12:24 MSK" name="reg" finished-at="2021-12-29T18:12:24 MSK" duration-ms="283" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="changePostTest()[pri:0, instance:ChangePostTest@551be9f6]" started-at="2021-12-29T18:12:24 MSK" name="changePostTest" finished-at="2021-12-29T18:12:25 MSK" duration-ms="949" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- changePostTest -->
        <test-method is-config="true" signature="delete()[pri:0, instance:ChangePostTest@551be9f6]" started-at="2021-12-29T18:12:25 MSK" name="delete" finished-at="2021-12-29T18:12:25 MSK" duration-ms="172" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
      </class> <!-- ChangePostTest -->
      <class name="SuccessRegistrationTest">
        <test-method signature="registrationTest()[pri:0, instance:SuccessRegistrationTest@2801827a]" started-at="2021-12-29T18:12:35 MSK" name="registrationTest" finished-at="2021-12-29T18:12:36 MSK" duration-ms="481" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registrationTest -->
      </class> <!-- SuccessRegistrationTest -->
      <class name="WrongCreatePostTest">
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongCreatePostTest@580fd26b]" started-at="2021-12-29T18:11:03 MSK" name="reg" finished-at="2021-12-29T18:11:04 MSK" duration-ms="614" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="createPostWithEmptyDescription()[pri:0, instance:WrongCreatePostTest@580fd26b]" started-at="2021-12-29T18:11:04 MSK" name="createPostWithEmptyDescription" finished-at="2021-12-29T18:11:09 MSK" duration-ms="5269" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPostWithEmptyDescription -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongCreatePostTest@580fd26b]" started-at="2021-12-29T18:11:09 MSK" name="delete" finished-at="2021-12-29T18:11:10 MSK" duration-ms="187" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongCreatePostTest@580fd26b]" started-at="2021-12-29T18:11:10 MSK" name="reg" finished-at="2021-12-29T18:11:10 MSK" duration-ms="286" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="createPostWithEmptyImage()[pri:0, instance:WrongCreatePostTest@580fd26b]" started-at="2021-12-29T18:11:10 MSK" name="createPostWithEmptyImage" finished-at="2021-12-29T18:11:10 MSK" duration-ms="200" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongCreatePostTest.createPostWithEmptyImage(WrongCreatePostTest.java:102)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPostWithEmptyImage -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongCreatePostTest@580fd26b]" started-at="2021-12-29T18:11:10 MSK" name="delete" finished-at="2021-12-29T18:11:10 MSK" duration-ms="179" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongCreatePostTest@580fd26b]" started-at="2021-12-29T18:11:10 MSK" name="reg" finished-at="2021-12-29T18:11:11 MSK" duration-ms="306" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="createPostWithEmptyTitle()[pri:0, instance:WrongCreatePostTest@580fd26b]" started-at="2021-12-29T18:11:11 MSK" name="createPostWithEmptyTitle" finished-at="2021-12-29T18:11:11 MSK" duration-ms="237" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongCreatePostTest.createPostWithEmptyTitle(WrongCreatePostTest.java:83)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPostWithEmptyTitle -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongCreatePostTest@580fd26b]" started-at="2021-12-29T18:11:11 MSK" name="delete" finished-at="2021-12-29T18:11:11 MSK" duration-ms="178" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongCreatePostTest@580fd26b]" started-at="2021-12-29T18:11:11 MSK" name="reg" finished-at="2021-12-29T18:11:11 MSK" duration-ms="295" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="createPostWithoutDescription()[pri:0, instance:WrongCreatePostTest@580fd26b]" started-at="2021-12-29T18:11:11 MSK" name="createPostWithoutDescription" finished-at="2021-12-29T18:11:11 MSK" duration-ms="199" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongCreatePostTest.createPostWithoutDescription(WrongCreatePostTest.java:121)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPostWithoutDescription -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongCreatePostTest@580fd26b]" started-at="2021-12-29T18:11:11 MSK" name="delete" finished-at="2021-12-29T18:11:12 MSK" duration-ms="176" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongCreatePostTest@580fd26b]" started-at="2021-12-29T18:11:12 MSK" name="reg" finished-at="2021-12-29T18:11:12 MSK" duration-ms="291" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="createPostWithoutImage()[pri:0, instance:WrongCreatePostTest@580fd26b]" started-at="2021-12-29T18:11:12 MSK" name="createPostWithoutImage" finished-at="2021-12-29T18:11:12 MSK" duration-ms="214" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongCreatePostTest.createPostWithoutImage(WrongCreatePostTest.java:140)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPostWithoutImage -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongCreatePostTest@580fd26b]" started-at="2021-12-29T18:11:12 MSK" name="delete" finished-at="2021-12-29T18:11:12 MSK" duration-ms="171" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongCreatePostTest@580fd26b]" started-at="2021-12-29T18:11:12 MSK" name="reg" finished-at="2021-12-29T18:11:13 MSK" duration-ms="289" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="createPostWithoutTitle()[pri:0, instance:WrongCreatePostTest@580fd26b]" started-at="2021-12-29T18:11:13 MSK" name="createPostWithoutTitle" finished-at="2021-12-29T18:11:13 MSK" duration-ms="202" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongCreatePostTest.createPostWithoutTitle(WrongCreatePostTest.java:159)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPostWithoutTitle -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongCreatePostTest@580fd26b]" started-at="2021-12-29T18:11:13 MSK" name="delete" finished-at="2021-12-29T18:11:13 MSK" duration-ms="186" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongCreatePostTest@580fd26b]" started-at="2021-12-29T18:11:13 MSK" name="reg" finished-at="2021-12-29T18:11:13 MSK" duration-ms="292" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="createPostWithoutToken()[pri:0, instance:WrongCreatePostTest@580fd26b]" started-at="2021-12-29T18:11:13 MSK" name="createPostWithoutToken" finished-at="2021-12-29T18:11:13 MSK" duration-ms="208" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongCreatePostTest.createPostWithoutToken(WrongCreatePostTest.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPostWithoutToken -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongCreatePostTest@580fd26b]" started-at="2021-12-29T18:11:13 MSK" name="delete" finished-at="2021-12-29T18:11:14 MSK" duration-ms="174" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
      </class> <!-- WrongCreatePostTest -->
      <class name="WrongLoginTest">
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:34 MSK" name="reg" finished-at="2021-12-29T18:11:35 MSK" duration-ms="282" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="correctEmailWithoutPassword()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:35 MSK" name="correctEmailWithoutPassword" finished-at="2021-12-29T18:11:35 MSK" duration-ms="186" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- correctEmailWithoutPassword -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:35 MSK" name="delete" finished-at="2021-12-29T18:11:35 MSK" duration-ms="174" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:35 MSK" name="reg" finished-at="2021-12-29T18:11:35 MSK" duration-ms="283" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="emptyEmail()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:35 MSK" name="emptyEmail" finished-at="2021-12-29T18:11:41 MSK" duration-ms="5236" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emptyEmail -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:41 MSK" name="delete" finished-at="2021-12-29T18:11:41 MSK" duration-ms="173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:41 MSK" name="reg" finished-at="2021-12-29T18:11:41 MSK" duration-ms="285" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="emptyEmailAndPassword()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:41 MSK" name="emptyEmailAndPassword" finished-at="2021-12-29T18:11:41 MSK" duration-ms="190" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:246)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emptyEmailAndPassword -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:41 MSK" name="delete" finished-at="2021-12-29T18:11:41 MSK" duration-ms="168" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:41 MSK" name="reg" finished-at="2021-12-29T18:11:42 MSK" duration-ms="291" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="emptyPassword()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:42 MSK" name="emptyPassword" finished-at="2021-12-29T18:11:42 MSK" duration-ms="317" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongLoginTest.emptyPassword(WrongLoginTest.java:221)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emptyPassword -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:42 MSK" name="delete" finished-at="2021-12-29T18:11:42 MSK" duration-ms="175" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:42 MSK" name="reg" finished-at="2021-12-29T18:11:43 MSK" duration-ms="282" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="incorrectEmail1()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:43 MSK" name="incorrectEmail1" finished-at="2021-12-29T18:11:43 MSK" duration-ms="208" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:50)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- incorrectEmail1 -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:43 MSK" name="delete" finished-at="2021-12-29T18:11:43 MSK" duration-ms="172" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:43 MSK" name="reg" finished-at="2021-12-29T18:11:43 MSK" duration-ms="304" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="incorrectEmail2()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:43 MSK" name="incorrectEmail2" finished-at="2021-12-29T18:11:43 MSK" duration-ms="202" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:74)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- incorrectEmail2 -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:43 MSK" name="delete" finished-at="2021-12-29T18:11:44 MSK" duration-ms="171" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:44 MSK" name="reg" finished-at="2021-12-29T18:11:44 MSK" duration-ms="280" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="incorrectEmail3()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:44 MSK" name="incorrectEmail3" finished-at="2021-12-29T18:11:44 MSK" duration-ms="196" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:99)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- incorrectEmail3 -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:44 MSK" name="delete" finished-at="2021-12-29T18:11:44 MSK" duration-ms="176" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:44 MSK" name="reg" finished-at="2021-12-29T18:11:45 MSK" duration-ms="313" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="incorrectEmail4()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:45 MSK" name="incorrectEmail4" finished-at="2021-12-29T18:11:45 MSK" duration-ms="197" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongLoginTest.incorrectEmail4(WrongLoginTest.java:125)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- incorrectEmail4 -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:45 MSK" name="delete" finished-at="2021-12-29T18:11:45 MSK" duration-ms="192" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:45 MSK" name="reg" finished-at="2021-12-29T18:11:45 MSK" duration-ms="280" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="incorrectEmail5()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:45 MSK" name="incorrectEmail5" finished-at="2021-12-29T18:11:46 MSK" duration-ms="329" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongLoginTest.incorrectEmail5(WrongLoginTest.java:149)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- incorrectEmail5 -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:46 MSK" name="delete" finished-at="2021-12-29T18:11:46 MSK" duration-ms="279" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:46 MSK" name="reg" finished-at="2021-12-29T18:11:46 MSK" duration-ms="289" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="userDoesNotExist()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:46 MSK" name="userDoesNotExist" finished-at="2021-12-29T18:11:51 MSK" duration-ms="5206" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongLoginTest.userDoesNotExist(WrongLoginTest.java:173)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userDoesNotExist -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:51 MSK" name="delete" finished-at="2021-12-29T18:11:52 MSK" duration-ms="177" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:52 MSK" name="reg" finished-at="2021-12-29T18:11:52 MSK" duration-ms="284" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="withoutEmail()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:52 MSK" name="withoutEmail" finished-at="2021-12-29T18:11:52 MSK" duration-ms="183" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongLoginTest.withoutEmail(WrongLoginTest.java:292)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- withoutEmail -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:52 MSK" name="delete" finished-at="2021-12-29T18:11:52 MSK" duration-ms="170" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:52 MSK" name="reg" finished-at="2021-12-29T18:11:52 MSK" duration-ms="280" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="withoutEmailAndPassword()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:52 MSK" name="withoutEmailAndPassword" finished-at="2021-12-29T18:11:53 MSK" duration-ms="186" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongLoginTest.withoutEmailAndPassword(WrongLoginTest.java:316)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- withoutEmailAndPassword -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongLoginTest@575cabf0]" started-at="2021-12-29T18:11:53 MSK" name="delete" finished-at="2021-12-29T18:11:53 MSK" duration-ms="172" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
      </class> <!-- WrongLoginTest -->
      <class name="WrongRegistrationTest">
        <test-method signature="regWithEmptyAllFields()[pri:0, instance:WrongRegistrationTest@6b37df8e]" started-at="2021-12-29T18:12:13 MSK" name="regWithEmptyAllFields" finished-at="2021-12-29T18:12:14 MSK" duration-ms="186" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- regWithEmptyAllFields -->
        <test-method signature="regWithExistingEmail()[pri:0, instance:WrongRegistrationTest@6b37df8e]" started-at="2021-12-29T18:12:14 MSK" name="regWithExistingEmail" finished-at="2021-12-29T18:12:14 MSK" duration-ms="456" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- regWithExistingEmail -->
        <test-method signature="regWithNullAllFields()[pri:0, instance:WrongRegistrationTest@6b37df8e]" started-at="2021-12-29T18:12:14 MSK" name="regWithNullAllFields" finished-at="2021-12-29T18:12:14 MSK" duration-ms="193" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- regWithNullAllFields -->
        <test-method signature="regWithWrongName()[pri:0, instance:WrongRegistrationTest@6b37df8e]" started-at="2021-12-29T18:12:14 MSK" name="regWithWrongName" finished-at="2021-12-29T18:12:15 MSK" duration-ms="198" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- regWithWrongName -->
        <test-method signature="regWithWrongRole()[pri:0, instance:WrongRegistrationTest@6b37df8e]" started-at="2021-12-29T18:12:15 MSK" name="regWithWrongRole" finished-at="2021-12-29T18:12:15 MSK" duration-ms="181" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- regWithWrongRole -->
        <test-method signature="regWithoutEmail()[pri:0, instance:WrongRegistrationTest@6b37df8e]" started-at="2021-12-29T18:12:15 MSK" name="regWithoutEmail" finished-at="2021-12-29T18:12:15 MSK" duration-ms="194" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- regWithoutEmail -->
        <test-method signature="regWithoutName()[pri:0, instance:WrongRegistrationTest@6b37df8e]" started-at="2021-12-29T18:12:15 MSK" name="regWithoutName" finished-at="2021-12-29T18:12:15 MSK" duration-ms="200" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- regWithoutName -->
        <test-method signature="regWithoutPassword()[pri:0, instance:WrongRegistrationTest@6b37df8e]" started-at="2021-12-29T18:12:15 MSK" name="regWithoutPassword" finished-at="2021-12-29T18:12:15 MSK" duration-ms="188" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongRegistrationTest.regWithoutPassword(WrongRegistrationTest.java:121)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- regWithoutPassword -->
        <test-method signature="regWithoutRole()[pri:0, instance:WrongRegistrationTest@6b37df8e]" started-at="2021-12-29T18:12:15 MSK" name="regWithoutRole" finished-at="2021-12-29T18:12:15 MSK" duration-ms="194" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongRegistrationTest.regWithoutRole(WrongRegistrationTest.java:139)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- regWithoutRole -->
      </class> <!-- WrongRegistrationTest -->
      <class name="GetFileTest">
        <test-method signature="getFileTest()[pri:0, instance:GetFileTest@3f6f3cc]" started-at="2021-12-29T18:11:31 MSK" name="getFileTest" finished-at="2021-12-29T18:11:32 MSK" duration-ms="351" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getFileTest -->
      </class> <!-- GetFileTest -->
      <class name="WrongDeletePostTest">
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongDeletePostTest@c3719e5]" started-at="2021-12-29T18:12:06 MSK" name="reg" finished-at="2021-12-29T18:12:06 MSK" duration-ms="299" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="deletePostTestWithWrongId()[pri:0, instance:WrongDeletePostTest@c3719e5]" started-at="2021-12-29T18:12:06 MSK" name="deletePostTestWithWrongId" finished-at="2021-12-29T18:12:06 MSK" duration-ms="381" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deletePostTestWithWrongId -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongDeletePostTest@c3719e5]" started-at="2021-12-29T18:12:07 MSK" name="delete" finished-at="2021-12-29T18:12:07 MSK" duration-ms="179" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongDeletePostTest@c3719e5]" started-at="2021-12-29T18:12:07 MSK" name="reg" finished-at="2021-12-29T18:12:07 MSK" duration-ms="284" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="deletePostTestWithoutToken()[pri:0, instance:WrongDeletePostTest@c3719e5]" started-at="2021-12-29T18:12:07 MSK" name="deletePostTestWithoutToken" finished-at="2021-12-29T18:12:13 MSK" duration-ms="5561" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deletePostTestWithoutToken -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongDeletePostTest@c3719e5]" started-at="2021-12-29T18:12:13 MSK" name="delete" finished-at="2021-12-29T18:12:13 MSK" duration-ms="193" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
      </class> <!-- WrongDeletePostTest -->
      <class name="GetPostTest">
        <test-method is-config="true" signature="reg()[pri:0, instance:GetPostTest@10b8b900]" started-at="2021-12-29T18:12:33 MSK" name="reg" finished-at="2021-12-29T18:12:34 MSK" duration-ms="275" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method is-config="true" signature="createPost()[pri:0, instance:GetPostTest@10b8b900]" started-at="2021-12-29T18:12:34 MSK" name="createPost" finished-at="2021-12-29T18:12:34 MSK" duration-ms="182" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPost -->
        <test-method signature="getPostTest()[pri:0, instance:GetPostTest@10b8b900]" started-at="2021-12-29T18:12:34 MSK" name="getPostTest" finished-at="2021-12-29T18:12:34 MSK" duration-ms="227" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPostTest -->
        <test-method is-config="true" signature="delete()[pri:0, instance:GetPostTest@10b8b900]" started-at="2021-12-29T18:12:34 MSK" name="delete" finished-at="2021-12-29T18:12:34 MSK" duration-ms="169" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:GetPostTest@10b8b900]" started-at="2021-12-29T18:12:34 MSK" name="reg" finished-at="2021-12-29T18:12:35 MSK" duration-ms="293" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method is-config="true" signature="createPost()[pri:0, instance:GetPostTest@10b8b900]" started-at="2021-12-29T18:12:35 MSK" name="createPost" finished-at="2021-12-29T18:12:35 MSK" duration-ms="191" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPost -->
        <test-method signature="getUserPostTest()[pri:0, instance:GetPostTest@10b8b900]" started-at="2021-12-29T18:12:35 MSK" name="getUserPostTest" finished-at="2021-12-29T18:12:35 MSK" duration-ms="242" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserPostTest -->
        <test-method is-config="true" signature="delete()[pri:0, instance:GetPostTest@10b8b900]" started-at="2021-12-29T18:12:35 MSK" name="delete" finished-at="2021-12-29T18:12:35 MSK" duration-ms="167" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
      </class> <!-- GetPostTest -->
      <class name="WrongGetUserPostTest">
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:11:54 MSK" name="reg" finished-at="2021-12-29T18:11:54 MSK" duration-ms="285" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method is-config="true" signature="createPost()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:11:54 MSK" name="createPost" finished-at="2021-12-29T18:11:55 MSK" duration-ms="219" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPost -->
        <test-method signature="getPostTest()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:11:55 MSK" name="getPostTest" finished-at="2021-12-29T18:11:55 MSK" duration-ms="233" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPostTest -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:11:55 MSK" name="delete" finished-at="2021-12-29T18:11:55 MSK" duration-ms="187" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:11:55 MSK" name="reg" finished-at="2021-12-29T18:11:55 MSK" duration-ms="280" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method is-config="true" signature="createPost()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:11:55 MSK" name="createPost" finished-at="2021-12-29T18:11:56 MSK" duration-ms="205" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPost -->
        <test-method signature="getUserPostTest()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:11:56 MSK" name="getUserPostTest" finished-at="2021-12-29T18:11:56 MSK" duration-ms="264" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserPostTest -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:11:56 MSK" name="delete" finished-at="2021-12-29T18:11:56 MSK" duration-ms="200" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:11:56 MSK" name="reg" finished-at="2021-12-29T18:11:56 MSK" duration-ms="276" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method is-config="true" signature="createPost()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:11:56 MSK" name="createPost" finished-at="2021-12-29T18:11:57 MSK" duration-ms="198" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPost -->
        <test-method signature="getUserPostWithPageEqual0()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:11:57 MSK" name="getUserPostWithPageEqual0" finished-at="2021-12-29T18:12:02 MSK" duration-ms="5201" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "java.util.List.contains(Object)" because "codes" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "java.util.List.contains(Object)" because "codes" is null
at WrongGetUserPostTest.getUserPostWithPageEqual0(WrongGetUserPostTest.java:105)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserPostWithPageEqual0 -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:12:02 MSK" name="delete" finished-at="2021-12-29T18:12:02 MSK" duration-ms="173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:12:02 MSK" name="reg" finished-at="2021-12-29T18:12:02 MSK" duration-ms="277" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method is-config="true" signature="createPost()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:12:02 MSK" name="createPost" finished-at="2021-12-29T18:12:02 MSK" duration-ms="190" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPost -->
        <test-method signature="getUserPostWithPerPageEqual0()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:12:02 MSK" name="getUserPostWithPerPageEqual0" finished-at="2021-12-29T18:12:03 MSK" duration-ms="210" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "java.util.List.contains(Object)" because "codes" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "java.util.List.contains(Object)" because "codes" is null
at WrongGetUserPostTest.getUserPostWithPerPageEqual0(WrongGetUserPostTest.java:129)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserPostWithPerPageEqual0 -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:12:03 MSK" name="delete" finished-at="2021-12-29T18:12:03 MSK" duration-ms="213" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:12:03 MSK" name="reg" finished-at="2021-12-29T18:12:03 MSK" duration-ms="279" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method is-config="true" signature="createPost()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:12:03 MSK" name="createPost" finished-at="2021-12-29T18:12:03 MSK" duration-ms="196" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPost -->
        <test-method signature="getUserPostWithoutPage()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:12:03 MSK" name="getUserPostWithoutPage" finished-at="2021-12-29T18:12:04 MSK" duration-ms="202" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Wrong "success" expected [true] but found [false],
Wrong "success" expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Wrong "success" expected [true] but found [false],
Wrong "success" expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongGetUserPostTest.getUserPostWithoutPage(WrongGetUserPostTest.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserPostWithoutPage -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:12:04 MSK" name="delete" finished-at="2021-12-29T18:12:04 MSK" duration-ms="176" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:12:04 MSK" name="reg" finished-at="2021-12-29T18:12:04 MSK" duration-ms="280" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method is-config="true" signature="createPost()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:12:04 MSK" name="createPost" finished-at="2021-12-29T18:12:04 MSK" duration-ms="192" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPost -->
        <test-method signature="getUserPostWithoutPerPage()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:12:04 MSK" name="getUserPostWithoutPerPage" finished-at="2021-12-29T18:12:04 MSK" duration-ms="187" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Wrong "success" expected [true] but found [false],
Wrong "success" expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Wrong "success" expected [true] but found [false],
Wrong "success" expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongGetUserPostTest.getUserPostWithoutPerPage(WrongGetUserPostTest.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserPostWithoutPerPage -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:12:04 MSK" name="delete" finished-at="2021-12-29T18:12:05 MSK" duration-ms="167" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:12:05 MSK" name="reg" finished-at="2021-12-29T18:12:05 MSK" duration-ms="291" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method is-config="true" signature="createPost()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:12:05 MSK" name="createPost" finished-at="2021-12-29T18:12:05 MSK" duration-ms="201" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPost -->
        <test-method signature="getUserPostWithoutToken()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:12:05 MSK" name="getUserPostWithoutToken" finished-at="2021-12-29T18:12:05 MSK" duration-ms="189" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Wrong "success" expected [true] but found [false],
Wrong "success" expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Wrong "success" expected [true] but found [false],
Wrong "success" expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongGetUserPostTest.getUserPostWithoutToken(WrongGetUserPostTest.java:83)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserPostWithoutToken -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongGetUserPostTest@4ea56bdb]" started-at="2021-12-29T18:12:05 MSK" name="delete" finished-at="2021-12-29T18:12:05 MSK" duration-ms="169" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
      </class> <!-- WrongGetUserPostTest -->
      <class name="UploadFileTest">
        <test-method signature="uploadFileTest()[pri:0, instance:UploadFileTest@7b351446]" started-at="2021-12-29T18:12:16 MSK" name="uploadFileTest" finished-at="2021-12-29T18:12:16 MSK" duration-ms="189" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- uploadFileTest -->
      </class> <!-- UploadFileTest -->
      <class name="SuccessAuthorizationTest">
        <test-method is-config="true" signature="reg()[pri:0, instance:SuccessAuthorizationTest@17fede14]" started-at="2021-12-29T18:11:14 MSK" name="reg" finished-at="2021-12-29T18:11:14 MSK" duration-ms="317" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="successAuthorizationTest()[pri:0, instance:SuccessAuthorizationTest@17fede14]" started-at="2021-12-29T18:11:14 MSK" name="successAuthorizationTest" finished-at="2021-12-29T18:11:14 MSK" duration-ms="456" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- successAuthorizationTest -->
        <test-method is-config="true" signature="delete()[pri:0, instance:SuccessAuthorizationTest@17fede14]" started-at="2021-12-29T18:11:14 MSK" name="delete" finished-at="2021-12-29T18:11:15 MSK" duration-ms="177" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
      </class> <!-- SuccessAuthorizationTest -->
      <class name="CreatePostTest">
        <test-method is-config="true" signature="reg()[pri:0, instance:CreatePostTest@1e225820]" started-at="2021-12-29T18:11:32 MSK" name="reg" finished-at="2021-12-29T18:11:32 MSK" duration-ms="286" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="createPostTest()[pri:0, instance:CreatePostTest@1e225820]" started-at="2021-12-29T18:11:32 MSK" name="createPostTest" finished-at="2021-12-29T18:11:33 MSK" duration-ms="387" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPostTest -->
        <test-method is-config="true" signature="delete()[pri:0, instance:CreatePostTest@1e225820]" started-at="2021-12-29T18:11:33 MSK" name="delete" finished-at="2021-12-29T18:11:33 MSK" duration-ms="181" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
      </class> <!-- CreatePostTest -->
      <class name="DeleteUserTest">
        <test-method signature="deleteUser()[pri:0, instance:DeleteUserTest@5f08fe00]" started-at="2021-12-29T18:12:16 MSK" name="deleteUser" finished-at="2021-12-29T18:12:16 MSK" duration-ms="527" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteUser -->
        <test-method signature="deleteWithEmptyToken()[pri:0, instance:DeleteUserTest@5f08fe00]" started-at="2021-12-29T18:12:16 MSK" name="deleteWithEmptyToken" finished-at="2021-12-29T18:12:18 MSK" duration-ms="1205" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteWithEmptyToken -->
        <test-method signature="deleteWithoutToken()[pri:0, instance:DeleteUserTest@5f08fe00]" started-at="2021-12-29T18:12:18 MSK" name="deleteWithoutToken" finished-at="2021-12-29T18:12:23 MSK" duration-ms="5697" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteWithoutToken -->
      </class> <!-- DeleteUserTest -->
      <class name="ChangeUserInfoTest">
        <test-method is-config="true" signature="reg()[pri:0, instance:ChangeUserInfoTest@497ed877]" started-at="2021-12-29T18:12:36 MSK" name="reg" finished-at="2021-12-29T18:12:36 MSK" duration-ms="300" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="changeUserInfoSuccess()[pri:0, instance:ChangeUserInfoTest@497ed877]" started-at="2021-12-29T18:12:36 MSK" name="changeUserInfoSuccess" finished-at="2021-12-29T18:12:36 MSK" duration-ms="218" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- changeUserInfoSuccess -->
        <test-method is-config="true" signature="delete()[pri:0, instance:ChangeUserInfoTest@497ed877]" started-at="2021-12-29T18:12:36 MSK" name="delete" finished-at="2021-12-29T18:12:36 MSK" duration-ms="171" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
      </class> <!-- ChangeUserInfoTest -->
      <class name="AllNewsPageGetTest">
        <test-method signature="allNewsPageGetTest()[pri:0, instance:AllNewsPageGetTest@433d9680]" started-at="2021-12-29T18:11:53 MSK" name="allNewsPageGetTest" finished-at="2021-12-29T18:11:53 MSK" duration-ms="274" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- allNewsPageGetTest -->
      </class> <!-- AllNewsPageGetTest -->
      <class name="WrongGetFileTest">
        <test-method signature="getFileWithoutFileNameTest()[pri:0, instance:WrongGetFileTest@39da5e49]" started-at="2021-12-29T18:12:05 MSK" name="getFileWithoutFileNameTest" finished-at="2021-12-29T18:12:06 MSK" duration-ms="437" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getFileWithoutFileNameTest -->
      </class> <!-- WrongGetFileTest -->
      <class name="WrongGetSpecificPostTest">
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongGetSpecificPostTest@1e40fbb3]" started-at="2021-12-29T18:12:25 MSK" name="reg" finished-at="2021-12-29T18:12:25 MSK" duration-ms="275" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method is-config="true" signature="createPost()[pri:0, instance:WrongGetSpecificPostTest@1e40fbb3]" started-at="2021-12-29T18:12:25 MSK" name="createPost" finished-at="2021-12-29T18:12:25 MSK" duration-ms="210" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPost -->
        <test-method signature="getPostTest()[pri:0, instance:WrongGetSpecificPostTest@1e40fbb3]" started-at="2021-12-29T18:12:25 MSK" name="getPostTest" finished-at="2021-12-29T18:12:26 MSK" duration-ms="239" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPostTest -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongGetSpecificPostTest@1e40fbb3]" started-at="2021-12-29T18:12:26 MSK" name="delete" finished-at="2021-12-29T18:12:26 MSK" duration-ms="171" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongGetSpecificPostTest@1e40fbb3]" started-at="2021-12-29T18:12:26 MSK" name="reg" finished-at="2021-12-29T18:12:26 MSK" duration-ms="288" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method is-config="true" signature="createPost()[pri:0, instance:WrongGetSpecificPostTest@1e40fbb3]" started-at="2021-12-29T18:12:26 MSK" name="createPost" finished-at="2021-12-29T18:12:26 MSK" duration-ms="196" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPost -->
        <test-method signature="getUserPostTest()[pri:0, instance:WrongGetSpecificPostTest@1e40fbb3]" started-at="2021-12-29T18:12:26 MSK" name="getUserPostTest" finished-at="2021-12-29T18:12:27 MSK" duration-ms="246" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserPostTest -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongGetSpecificPostTest@1e40fbb3]" started-at="2021-12-29T18:12:27 MSK" name="delete" finished-at="2021-12-29T18:12:27 MSK" duration-ms="177" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongGetSpecificPostTest@1e40fbb3]" started-at="2021-12-29T18:12:27 MSK" name="reg" finished-at="2021-12-29T18:12:27 MSK" duration-ms="287" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method is-config="true" signature="createPost()[pri:0, instance:WrongGetSpecificPostTest@1e40fbb3]" started-at="2021-12-29T18:12:27 MSK" name="createPost" finished-at="2021-12-29T18:12:27 MSK" duration-ms="182" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPost -->
        <test-method signature="getPostWithoutPageTest()[pri:0, instance:WrongGetSpecificPostTest@1e40fbb3]" started-at="2021-12-29T18:12:27 MSK" name="getPostWithoutPageTest" finished-at="2021-12-29T18:12:27 MSK" duration-ms="185" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongGetSpecificPostTest.getPostWithoutPageTest(WrongGetSpecificPostTest.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPostWithoutPageTest -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongGetSpecificPostTest@1e40fbb3]" started-at="2021-12-29T18:12:27 MSK" name="delete" finished-at="2021-12-29T18:12:28 MSK" duration-ms="178" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongGetSpecificPostTest@1e40fbb3]" started-at="2021-12-29T18:12:28 MSK" name="reg" finished-at="2021-12-29T18:12:28 MSK" duration-ms="283" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method is-config="true" signature="createPost()[pri:0, instance:WrongGetSpecificPostTest@1e40fbb3]" started-at="2021-12-29T18:12:28 MSK" name="createPost" finished-at="2021-12-29T18:12:28 MSK" duration-ms="186" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPost -->
        <test-method signature="getPostWithoutPerPageTest()[pri:0, instance:WrongGetSpecificPostTest@1e40fbb3]" started-at="2021-12-29T18:12:28 MSK" name="getPostWithoutPerPageTest" finished-at="2021-12-29T18:12:33 MSK" duration-ms="5208" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false],
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongGetSpecificPostTest.getPostWithoutPerPageTest(WrongGetSpecificPostTest.java:63)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPostWithoutPerPageTest -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongGetSpecificPostTest@1e40fbb3]" started-at="2021-12-29T18:12:33 MSK" name="delete" finished-at="2021-12-29T18:12:33 MSK" duration-ms="182" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
      </class> <!-- WrongGetSpecificPostTest -->
      <class name="WrongChangePostTest">
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:36 MSK" name="reg" finished-at="2021-12-29T18:12:37 MSK" duration-ms="282" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="wrongChangePostTestWithEmptyDescription()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:37 MSK" name="wrongChangePostTestWithEmptyDescription" finished-at="2021-12-29T18:12:37 MSK" duration-ms="547" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wrongChangePostTestWithEmptyDescription -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:37 MSK" name="delete" finished-at="2021-12-29T18:12:37 MSK" duration-ms="169" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:37 MSK" name="reg" finished-at="2021-12-29T18:12:38 MSK" duration-ms="276" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="wrongChangePostTestWithEmptyTags()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:38 MSK" name="wrongChangePostTestWithEmptyTags" finished-at="2021-12-29T18:12:38 MSK" duration-ms="544" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wrongChangePostTestWithEmptyTags -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:38 MSK" name="delete" finished-at="2021-12-29T18:12:38 MSK" duration-ms="168" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:38 MSK" name="reg" finished-at="2021-12-29T18:12:39 MSK" duration-ms="269" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="wrongChangePostTestWithEmptyTitle()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:39 MSK" name="wrongChangePostTestWithEmptyTitle" finished-at="2021-12-29T18:12:44 MSK" duration-ms="5529" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wrongChangePostTestWithEmptyTitle -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:44 MSK" name="delete" finished-at="2021-12-29T18:12:44 MSK" duration-ms="168" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:44 MSK" name="reg" finished-at="2021-12-29T18:12:45 MSK" duration-ms="307" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="wrongChangePostTestWithWrongId()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:45 MSK" name="wrongChangePostTestWithWrongId" finished-at="2021-12-29T18:12:45 MSK" duration-ms="386" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wrongChangePostTestWithWrongId -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:45 MSK" name="delete" finished-at="2021-12-29T18:12:45 MSK" duration-ms="173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:45 MSK" name="reg" finished-at="2021-12-29T18:12:45 MSK" duration-ms="285" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="wrongChangePostTestWithoutDescription()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:45 MSK" name="wrongChangePostTestWithoutDescription" finished-at="2021-12-29T18:12:46 MSK" duration-ms="555" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wrongChangePostTestWithoutDescription -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:46 MSK" name="delete" finished-at="2021-12-29T18:12:46 MSK" duration-ms="166" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:46 MSK" name="reg" finished-at="2021-12-29T18:12:46 MSK" duration-ms="279" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="wrongChangePostTestWithoutImage()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:46 MSK" name="wrongChangePostTestWithoutImage" finished-at="2021-12-29T18:12:47 MSK" duration-ms="548" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wrongChangePostTestWithoutImage -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:47 MSK" name="delete" finished-at="2021-12-29T18:12:47 MSK" duration-ms="168" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:47 MSK" name="reg" finished-at="2021-12-29T18:12:48 MSK" duration-ms="397" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="wrongChangePostTestWithoutTitle()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:48 MSK" name="wrongChangePostTestWithoutTitle" finished-at="2021-12-29T18:12:48 MSK" duration-ms="565" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wrongChangePostTestWithoutTitle -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:48 MSK" name="delete" finished-at="2021-12-29T18:12:48 MSK" duration-ms="181" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:48 MSK" name="reg" finished-at="2021-12-29T18:12:49 MSK" duration-ms="290" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="wrongChangePostTestWithoutToken()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:49 MSK" name="wrongChangePostTestWithoutToken" finished-at="2021-12-29T18:12:54 MSK" duration-ms="5534" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wrongChangePostTestWithoutToken -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongChangePostTest@73e1ecd0]" started-at="2021-12-29T18:12:54 MSK" name="delete" finished-at="2021-12-29T18:12:54 MSK" duration-ms="173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
      </class> <!-- WrongChangePostTest -->
      <class name="WrongChangeUserInfoTest">
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:15 MSK" name="reg" finished-at="2021-12-29T18:11:15 MSK" duration-ms="286" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="withEmptyEmail()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:15 MSK" name="withEmptyEmail" finished-at="2021-12-29T18:11:20 MSK" duration-ms="5216" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- withEmptyEmail -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:20 MSK" name="delete" finished-at="2021-12-29T18:11:20 MSK" duration-ms="179" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:20 MSK" name="reg" finished-at="2021-12-29T18:11:21 MSK" duration-ms="289" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="withEmptyEmailName()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:21 MSK" name="withEmptyEmailName" finished-at="2021-12-29T18:11:21 MSK" duration-ms="214" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- withEmptyEmailName -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:21 MSK" name="delete" finished-at="2021-12-29T18:11:21 MSK" duration-ms="172" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:21 MSK" name="reg" finished-at="2021-12-29T18:11:21 MSK" duration-ms="284" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="withEmptyName()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:21 MSK" name="withEmptyName" finished-at="2021-12-29T18:11:21 MSK" duration-ms="206" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- withEmptyName -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:21 MSK" name="delete" finished-at="2021-12-29T18:11:22 MSK" duration-ms="171" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:22 MSK" name="reg" finished-at="2021-12-29T18:11:22 MSK" duration-ms="280" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="withWrongEmail()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:22 MSK" name="withWrongEmail" finished-at="2021-12-29T18:11:22 MSK" duration-ms="212" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Wrong "success" expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Wrong "success" expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongChangeUserInfoTest.withWrongEmail(WrongChangeUserInfoTest.java:76)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- withWrongEmail -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:22 MSK" name="delete" finished-at="2021-12-29T18:11:22 MSK" duration-ms="174" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:22 MSK" name="reg" finished-at="2021-12-29T18:11:23 MSK" duration-ms="275" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="withWrongName()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:23 MSK" name="withWrongName" finished-at="2021-12-29T18:11:23 MSK" duration-ms="195" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- withWrongName -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:23 MSK" name="delete" finished-at="2021-12-29T18:11:23 MSK" duration-ms="173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:23 MSK" name="reg" finished-at="2021-12-29T18:11:23 MSK" duration-ms="280" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="withoutAvatar()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:23 MSK" name="withoutAvatar" finished-at="2021-12-29T18:11:23 MSK" duration-ms="192" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- withoutAvatar -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:23 MSK" name="delete" finished-at="2021-12-29T18:11:24 MSK" duration-ms="169" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:24 MSK" name="reg" finished-at="2021-12-29T18:11:24 MSK" duration-ms="286" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="withoutEmail()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:24 MSK" name="withoutEmail" finished-at="2021-12-29T18:11:24 MSK" duration-ms="200" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- withoutEmail -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:24 MSK" name="delete" finished-at="2021-12-29T18:11:24 MSK" duration-ms="170" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:24 MSK" name="reg" finished-at="2021-12-29T18:11:25 MSK" duration-ms="307" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="withoutName()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:25 MSK" name="withoutName" finished-at="2021-12-29T18:11:25 MSK" duration-ms="195" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- withoutName -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:25 MSK" name="delete" finished-at="2021-12-29T18:11:25 MSK" duration-ms="176" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:25 MSK" name="reg" finished-at="2021-12-29T18:11:25 MSK" duration-ms="281" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="withoutRole()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:25 MSK" name="withoutRole" finished-at="2021-12-29T18:11:30 MSK" duration-ms="5244" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- withoutRole -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:30 MSK" name="delete" finished-at="2021-12-29T18:11:31 MSK" duration-ms="171" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:31 MSK" name="reg" finished-at="2021-12-29T18:11:31 MSK" duration-ms="315" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="withoutToken()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:31 MSK" name="withoutToken" finished-at="2021-12-29T18:11:31 MSK" duration-ms="339" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"codes" does not contain correct error code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at WrongChangeUserInfoTest.withoutToken(WrongChangeUserInfoTest.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- withoutToken -->
        <test-method is-config="true" signature="delete()[pri:0, instance:WrongChangeUserInfoTest@2272cbb0]" started-at="2021-12-29T18:11:31 MSK" name="delete" finished-at="2021-12-29T18:11:31 MSK" duration-ms="188" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
      </class> <!-- WrongChangeUserInfoTest -->
      <class name="DeletePostTest">
        <test-method is-config="true" signature="reg()[pri:0, instance:DeletePostTest@6ad1701a]" started-at="2021-12-29T18:11:53 MSK" name="reg" finished-at="2021-12-29T18:11:53 MSK" duration-ms="307" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="deletePostTest()[pri:0, instance:DeletePostTest@6ad1701a]" started-at="2021-12-29T18:11:53 MSK" name="deletePostTest" finished-at="2021-12-29T18:11:54 MSK" duration-ms="629" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deletePostTest -->
        <test-method is-config="true" signature="delete()[pri:0, instance:DeletePostTest@6ad1701a]" started-at="2021-12-29T18:11:54 MSK" name="delete" finished-at="2021-12-29T18:11:54 MSK" duration-ms="171" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
      </class> <!-- DeletePostTest -->
      <class name="GetUserInfoTest">
        <test-method is-config="true" signature="reg()[pri:0, instance:GetUserInfoTest@7741771e]" started-at="2021-12-29T18:11:33 MSK" name="reg" finished-at="2021-12-29T18:11:33 MSK" duration-ms="286" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="getUserInfoByIdTest()[pri:0, instance:GetUserInfoTest@7741771e]" started-at="2021-12-29T18:11:33 MSK" name="getUserInfoByIdTest" finished-at="2021-12-29T18:11:33 MSK" duration-ms="273" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserInfoByIdTest -->
        <test-method is-config="true" signature="delete()[pri:0, instance:GetUserInfoTest@7741771e]" started-at="2021-12-29T18:11:33 MSK" name="delete" finished-at="2021-12-29T18:11:33 MSK" duration-ms="171" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="reg()[pri:0, instance:GetUserInfoTest@7741771e]" started-at="2021-12-29T18:11:33 MSK" name="reg" finished-at="2021-12-29T18:11:34 MSK" duration-ms="321" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
        <test-method signature="getUsers()[pri:0, instance:GetUserInfoTest@7741771e]" started-at="2021-12-29T18:11:34 MSK" name="getUsers" finished-at="2021-12-29T18:11:34 MSK" duration-ms="578" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUsers -->
        <test-method is-config="true" signature="delete()[pri:0, instance:GetUserInfoTest@7741771e]" started-at="2021-12-29T18:11:34 MSK" name="delete" finished-at="2021-12-29T18:11:34 MSK" duration-ms="175" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
      </class> <!-- GetUserInfoTest -->
      <class name="WrongGetUserInfoTest">
        <test-method signature="withWrongUserId()[pri:0, instance:WrongGetUserInfoTest@7fd99443]" started-at="2021-12-29T18:12:23 MSK" name="withWrongUserId" finished-at="2021-12-29T18:12:24 MSK" duration-ms="212" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- withWrongUserId -->
      </class> <!-- WrongGetUserInfoTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
