<?xml version="1.0" encoding="UTF-8" ?>
<testsuite tests="87" failures="26" name="TestSuite" time="25.802" errors="0" skipped="0">
  <properties>
    <property name="java.runtime.name" value="OpenJDK Runtime Environment"/>
    <property name="java.vm.version" value="17.0.1+0"/>
    <property name="sun.boot.library.path" value="/usr/local/Cellar/openjdk/17.0.1/libexec/openjdk.jdk/Contents/Home/lib"/>
    <property name="maven.multiModuleProjectDirectory" value="/Users/dunice/Projects/RestAssured"/>
    <property name="java.vm.vendor" value="Homebrew"/>
    <property name="java.vendor.url" value="https://github.com/Homebrew/homebrew-core/issues"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="path.separator" value=":"/>
    <property name="java.vm.name" value="OpenJDK 64-Bit Server VM"/>
    <property name="user.country" value="RU"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/Users/dunice/Projects/RestAssured"/>
    <property name="java.vm.compressedOopsMode" value="Zero based"/>
    <property name="java.runtime.version" value="17.0.1+0"/>
    <property name="os.arch" value="x86_64"/>
    <property name="java.io.tmpdir" value="/var/folders/vh/yn_xcpnx0cd6qwtfs_v555km0000gn/T/"/>
    <property name="line.separator" value="
"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="os.name" value="Mac OS X"/>
    <property name="classworlds.conf" value="/usr/local/Cellar/maven/3.8.3/libexec/bin/m2.conf"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.library.path" value="/Users/dunice/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:."/>
    <property name="maven.conf" value="/usr/local/Cellar/maven/3.8.3/libexec/conf"/>
    <property name="jdk.debug" value="release"/>
    <property name="java.class.version" value="61.0"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="os.version" value="11.6"/>
    <property name="library.jansi.path" value="/usr/local/Cellar/maven/3.8.3/libexec/lib/jansi-native"/>
    <property name="http.nonProxyHosts" value="local|*.local|169.254/16|*.169.254/16"/>
    <property name="user.home" value="/Users/dunice"/>
    <property name="user.timezone" value="Europe/Moscow"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="java.specification.version" value="17"/>
    <property name="user.name" value="dunice"/>
    <property name="java.class.path" value="/usr/local/Cellar/maven/3.8.3/libexec/boot/plexus-classworlds-2.6.0.jar"/>
    <property name="java.vm.specification.version" value="17"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher clean test"/>
    <property name="java.home" value="/usr/local/Cellar/openjdk/17.0.1/libexec/openjdk.jdk/Contents/Home"/>
    <property name="user.language" value="ru"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="java.vm.info" value="mixed mode, sharing"/>
    <property name="java.version" value="17.0.1"/>
    <property name="native.encoding" value="UTF-8"/>
    <property name="java.vendor" value="Homebrew"/>
    <property name="sun.stderr.encoding" value="UTF-8"/>
    <property name="maven.home" value="/usr/local/Cellar/maven/3.8.3/libexec"/>
    <property name="file.separator" value="/"/>
    <property name="java.version.date" value="2021-10-19"/>
    <property name="java.vendor.url.bug" value="https://github.com/Homebrew/homebrew-core/issues"/>
    <property name="sun.io.unicode.encoding" value="UnicodeBig"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="java.vendor.version" value="Homebrew"/>
    <property name="sun.stdout.encoding" value="UTF-8"/>
    <property name="socksNonProxyHosts" value="local|*.local|169.254/16|*.169.254/16"/>
    <property name="ftp.nonProxyHosts" value="local|*.local|169.254/16|*.169.254/16"/>
  </properties>
  <testcase classname="WrongCreatePostTest" name="createPostWithEmptyDescription" time="0.22"/>
  <testcase classname="WrongCreatePostTest" name="createPostWithEmptyImage" time="0.211">
    <failure message="The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongCreatePostTest.createPostWithEmptyImage(WrongCreatePostTest.java:101)
</failure>
  </testcase>
  <testcase classname="WrongCreatePostTest" name="createPostWithEmptyTitle" time="0.219"/>
  <testcase classname="WrongCreatePostTest" name="createPostWithoutDescription" time="0.205"/>
  <testcase classname="WrongCreatePostTest" name="createPostWithoutImage" time="0.193"/>
  <testcase classname="WrongCreatePostTest" name="createPostWithoutTitle" time="0.203"/>
  <testcase classname="WrongCreatePostTest" name="createPostWithoutToken" time="0.219">
    <failure message="The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongCreatePostTest.createPostWithoutToken(WrongCreatePostTest.java:44)
</failure>
  </testcase>
  <testcase classname="SuccessAuthorizationTest" name="successAuthorizationTest" time="0.457"/>
  <testcase classname="WrongChangeUserInfoTest" name="withEmptyEmail" time="0.207"/>
  <testcase classname="WrongChangeUserInfoTest" name="withEmptyEmailName" time="0.191"/>
  <testcase classname="WrongChangeUserInfoTest" name="withEmptyName" time="0.203"/>
  <testcase classname="WrongChangeUserInfoTest" name="withWrongEmail" time="0.221">
    <failure message="The following asserts failed:
	Wrong &quot;success&quot; expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	Wrong &quot;success&quot; expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongChangeUserInfoTest.withWrongEmail(WrongChangeUserInfoTest.java:76)
</failure>
    <system-out>Cannot invoke &quot;java.util.List.contains(Object)&quot; because &quot;codes&quot; is null
</system-out>
  </testcase>
  <testcase classname="WrongChangeUserInfoTest" name="withWrongName" time="0.195"/>
  <testcase classname="WrongChangeUserInfoTest" name="withoutAvatar" time="0.19"/>
  <testcase classname="WrongChangeUserInfoTest" name="withoutEmail" time="0.192"/>
  <testcase classname="WrongChangeUserInfoTest" name="withoutName" time="0.198"/>
  <testcase classname="WrongChangeUserInfoTest" name="withoutRole" time="0.199"/>
  <testcase classname="WrongChangeUserInfoTest" name="withoutToken" time="0.188">
    <failure message="The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongChangeUserInfoTest.withoutToken(WrongChangeUserInfoTest.java:53)
</failure>
  </testcase>
  <testcase classname="GetFileTest" name="getFileTest" time="0.362"/>
  <testcase classname="CreatePostTest" name="createPostTest" time="0.37"/>
  <testcase classname="GetUserInfoTest" name="getUserInfoByIdTest" time="0.286"/>
  <testcase classname="GetUserInfoTest" name="getUsers" time="0.646"/>
  <testcase classname="WrongLoginTest" name="correctEmailWithoutPassword" time="0.192"/>
  <testcase classname="WrongLoginTest" name="emptyEmail" time="0.202"/>
  <testcase classname="WrongLoginTest" name="emptyEmailAndPassword" time="0.19">
    <failure message="The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:245)
</failure>
  </testcase>
  <testcase classname="WrongLoginTest" name="emptyPassword" time="0.3"/>
  <testcase classname="WrongLoginTest" name="incorrectEmail1" time="0.205">
    <failure message="The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:49)
</failure>
  </testcase>
  <testcase classname="WrongLoginTest" name="incorrectEmail2" time="0.187">
    <failure message="The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:73)
</failure>
  </testcase>
  <testcase classname="WrongLoginTest" name="incorrectEmail3" time="0.188">
    <failure message="The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:98)
</failure>
  </testcase>
  <testcase classname="WrongLoginTest" name="incorrectEmail4" time="0.185">
    <failure message="The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongLoginTest.incorrectEmail4(WrongLoginTest.java:124)
</failure>
  </testcase>
  <testcase classname="WrongLoginTest" name="incorrectEmail5" time="0.201">
    <failure message="The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongLoginTest.incorrectEmail5(WrongLoginTest.java:148)
</failure>
  </testcase>
  <testcase classname="WrongLoginTest" name="userDoesNotExist" time="0.21"/>
  <testcase classname="WrongLoginTest" name="withoutEmail" time="0.189">
    <failure message="The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongLoginTest.withoutEmail(WrongLoginTest.java:291)
</failure>
  </testcase>
  <testcase classname="WrongLoginTest" name="withoutEmailAndPassword" time="0.185">
    <failure message="The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false],
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false],
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongLoginTest.withoutEmailAndPassword(WrongLoginTest.java:315)
</failure>
  </testcase>
  <testcase classname="AllNewsPageGetTest" name="allNewsPageGetTest" time="0.274"/>
  <testcase classname="DeletePostTest" name="deletePostTest" time="0.601"/>
  <testcase classname="WrongGetUserPostTest" name="getPostTest" time="0.241"/>
  <testcase classname="WrongGetUserPostTest" name="getUserPostTest" time="0.266"/>
  <testcase classname="WrongGetUserPostTest" name="getUserPostWithPageEqual0" time="0.194">
    <failure message="The following asserts failed:
	Wrong &quot;success&quot; expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	Wrong &quot;success&quot; expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongGetUserPostTest.getUserPostWithPageEqual0(WrongGetUserPostTest.java:109)
</failure>
    <system-out>Cannot invoke &quot;java.util.List.contains(Object)&quot; because &quot;codes&quot; is null
</system-out>
  </testcase>
  <testcase classname="WrongGetUserPostTest" name="getUserPostWithPerPageEqual0" time="0.196">
    <failure message="The following asserts failed:
	Wrong &quot;success&quot; expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	Wrong &quot;success&quot; expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongGetUserPostTest.getUserPostWithPerPageEqual0(WrongGetUserPostTest.java:138)
</failure>
    <system-out>Cannot invoke &quot;java.util.List.contains(Object)&quot; because &quot;codes&quot; is null
</system-out>
  </testcase>
  <testcase classname="WrongGetUserPostTest" name="getUserPostWithoutPage" time="0.197">
    <failure message="The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongGetUserPostTest.getUserPostWithoutPage(WrongGetUserPostTest.java:35)
</failure>
  </testcase>
  <testcase classname="WrongGetUserPostTest" name="getUserPostWithoutPerPage" time="0.203">
    <failure message="The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongGetUserPostTest.getUserPostWithoutPerPage(WrongGetUserPostTest.java:58)
</failure>
  </testcase>
  <testcase classname="WrongGetUserPostTest" name="getUserPostWithoutToken" time="0.213"/>
  <testcase classname="WrongGetFileTest" name="getFileWithoutFileNameTest" time="0.437"/>
  <testcase classname="WrongDeletePostTest" name="deletePostTestWithWrongId" time="0.391"/>
  <testcase classname="WrongDeletePostTest" name="deletePostTestWithoutToken" time="0.636"/>
  <testcase classname="WrongGetPostTest" name="getPostWithPageEqual0" time="0.202">
    <failure message="The following asserts failed:
	Wrong &quot;success&quot; expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	Wrong &quot;success&quot; expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongGetPostTest.getPostWithPageEqual0(WrongGetPostTest.java:88)
</failure>
    <system-out>Cannot invoke &quot;java.util.List.contains(Object)&quot; because &quot;codes&quot; is null
</system-out>
  </testcase>
  <testcase classname="WrongGetPostTest" name="getPostWithPerPageEqual0" time="0.201">
    <failure message="The following asserts failed:
	Wrong &quot;success&quot; expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	Wrong &quot;success&quot; expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongGetPostTest.getPostWithPerPageEqual0(WrongGetPostTest.java:118)
</failure>
    <system-out>Cannot invoke &quot;java.util.List.contains(Object)&quot; because &quot;codes&quot; is null
</system-out>
  </testcase>
  <testcase classname="WrongGetPostTest" name="getPostWithoutPage" time="0.244">
    <failure message="The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongGetPostTest.getPostWithoutPage(WrongGetPostTest.java:37)
</failure>
  </testcase>
  <testcase classname="WrongGetPostTest" name="getPostWithoutPerPage" time="0.203">
    <failure message="The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongGetPostTest.getPostWithoutPerPage(WrongGetPostTest.java:60)
</failure>
  </testcase>
  <testcase classname="WrongRegistrationTest" name="regWithEmptyAllFields" time="0.197"/>
  <testcase classname="WrongRegistrationTest" name="regWithEmptyEmail" time="0.196"/>
  <testcase classname="WrongRegistrationTest" name="regWithEmptyName" time="0.191"/>
  <testcase classname="WrongRegistrationTest" name="regWithEmptyPassword" time="0.291">
    <failure message="1 expectation failed.
Expected status code &lt;400&gt; but was &lt;200&gt;.
" type="java.lang.AssertionError">java.lang.AssertionError: 1 expectation failed.
Expected status code &lt;400&gt; but was &lt;200&gt;.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:493)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.validate(ResponseSpecificationImpl.groovy:92)
	at io.restassured.internal.ValidatableResponseOptionsImpl.spec(ValidatableResponseOptionsImpl.java:288)
	at io.restassured.internal.ValidatableResponseImpl.super$2$spec(ValidatableResponseImpl.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
	at io.restassured.internal.ValidatableResponseImpl.spec(ValidatableResponseImpl.groovy:76)
	at io.restassured.internal.ValidatableResponseImpl.spec(ValidatableResponseImpl.groovy)
	at Methods.wrongRegistration(Methods.java:47)
	at WrongRegistrationTest.regWithEmptyPassword(WrongRegistrationTest.java:173)
</failure>
  </testcase>
  <testcase classname="WrongRegistrationTest" name="regWithEmptyRole" time="0.184"/>
  <testcase classname="WrongRegistrationTest" name="regWithExistingEmail" time="0.169">
    <failure message="1 expectation failed.
Expected status code &lt;200&gt; but was &lt;400&gt;.
" type="java.lang.AssertionError">java.lang.AssertionError: 1 expectation failed.
Expected status code &lt;200&gt; but was &lt;400&gt;.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:493)
	at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.validate(ResponseSpecificationImpl.groovy:92)
	at io.restassured.internal.ValidatableResponseOptionsImpl.spec(ValidatableResponseOptionsImpl.java:288)
	at io.restassured.internal.ValidatableResponseImpl.super$2$spec(ValidatableResponseImpl.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
	at io.restassured.internal.ValidatableResponseImpl.spec(ValidatableResponseImpl.groovy:76)
	at io.restassured.internal.ValidatableResponseImpl.spec(ValidatableResponseImpl.groovy)
	at Methods.registration(Methods.java:36)
	at WrongRegistrationTest.regWithExistingEmail(WrongRegistrationTest.java:245)
</failure>
  </testcase>
  <testcase classname="WrongRegistrationTest" name="regWithNullAllFields" time="0.182"/>
  <testcase classname="WrongRegistrationTest" name="regWithWrongName" time="0.195"/>
  <testcase classname="WrongRegistrationTest" name="regWithWrongRole" time="0.187"/>
  <testcase classname="WrongRegistrationTest" name="regWithoutAvatar" time="0.185"/>
  <testcase classname="WrongRegistrationTest" name="regWithoutEmail" time="0.187">
    <failure message="The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongRegistrationTest.regWithoutEmail(WrongRegistrationTest.java:127)
</failure>
  </testcase>
  <testcase classname="WrongRegistrationTest" name="regWithoutName" time="0.182"/>
  <testcase classname="WrongRegistrationTest" name="regWithoutPassword" time="0.185"/>
  <testcase classname="WrongRegistrationTest" name="regWithoutRole" time="0.184">
    <failure message="The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongRegistrationTest.regWithoutRole(WrongRegistrationTest.java:235)
</failure>
  </testcase>
  <testcase classname="WrongUploadFileTest" name="uploadFileWithNonFormDataTest" time="0.188"/>
  <testcase classname="UploadFileTest" name="uploadFileTest" time="0.185"/>
  <testcase classname="DeleteUserTest" name="deleteUser" time="0.505"/>
  <testcase classname="DeleteUserTest" name="deleteWithEmptyToken" time="0.659"/>
  <testcase classname="DeleteUserTest" name="deleteWithoutToken" time="0.819"/>
  <testcase classname="WrongGetUserInfoTest" name="withWrongUserId" time="0.201"/>
  <testcase classname="ChangePostTest" name="changePostTest" time="0.947"/>
  <testcase classname="WrongGetSpecificPostTest" name="getPostTest" time="0.237"/>
  <testcase classname="WrongGetSpecificPostTest" name="getUserPostTest" time="0.231"/>
  <testcase classname="WrongGetSpecificPostTest" name="getPostWithoutPageTest" time="0.263">
    <failure message="The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongGetSpecificPostTest.getPostWithoutPageTest(WrongGetSpecificPostTest.java:38)
</failure>
  </testcase>
  <testcase classname="WrongGetSpecificPostTest" name="getPostWithoutPerPageTest" time="0.191">
    <failure message="The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false],
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	&quot;codes&quot; does not contain correct error code expected [true] but found [false],
	&quot;codes&quot; does not contain correct error code expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at WrongGetSpecificPostTest.getPostWithoutPerPageTest(WrongGetSpecificPostTest.java:63)
</failure>
  </testcase>
  <testcase classname="GetPostTest" name="getPostTest" time="0.232"/>
  <testcase classname="GetPostTest" name="getUserPostTest" time="0.237"/>
  <testcase classname="SuccessRegistrationTest" name="registrationTest" time="0.485"/>
  <testcase classname="ChangeUserInfoTest" name="changeUserInfoSuccess" time="0.208"/>
  <testcase classname="WrongChangePostTest" name="wrongChangePostTestWithEmptyDescription" time="0.534"/>
  <testcase classname="WrongChangePostTest" name="wrongChangePostTestWithEmptyTags" time="0.546"/>
  <testcase classname="WrongChangePostTest" name="wrongChangePostTestWithEmptyTitle" time="0.888"/>
  <testcase classname="WrongChangePostTest" name="wrongChangePostTestWithWrongId" time="0.366"/>
  <testcase classname="WrongChangePostTest" name="wrongChangePostTestWithoutDescription" time="0.59"/>
  <testcase classname="WrongChangePostTest" name="wrongChangePostTestWithoutImage" time="0.568"/>
  <testcase classname="WrongChangePostTest" name="wrongChangePostTestWithoutTitle" time="0.546"/>
  <testcase classname="WrongChangePostTest" name="wrongChangePostTestWithoutToken" time="0.753"/>
</testsuite>